---
title: "PMC Kelp bibliometrics"
author: "Luis Malpica"
date: "Apr, 2019"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---
```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = FALSE)
#code_folding: hide
```

```{r Libraries & data, include=F, cache=FALSE, message=F}
rm(list = ls())

#load
#library(plyr)
#library(tidyr)
#library(reshape2)
library(dplyr)
library(ggplot2)
#library(viridis)

#Custom theme for ggplot####
theme_gg <- function(base_size = 11, base_family = "") {
  theme_light() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      strip.background = element_rect(fill = NA, colour = NA),
      strip.text.x = element_text(colour = "grey10"),
      axis.text = element_text(colour = "grey20",size=14),
      axis.title = element_text(colour = "grey20",size=18),
      legend.title = element_text(colour = "grey20", size = rel(1.2)),
      panel.border = element_rect(fill = NA, colour = "grey70", size = 1),
      legend.key.size = unit(0.8, "lines"),
      legend.text = element_text(size = rel(1), colour = "grey20"),
      legend.key = element_rect(colour = NA)
    )
}
```

```{r Data manipulation, include=T}
#Read and manipulate data####
d <- read.table("data/Biblio.csv",sep=",", header=T)

#Plot of # of type of publication 
ggplot(d, aes(Type, fill = Type)) +
  geom_bar() +  
  scale_fill_grey() +
  xlab('Categoría de publicación') +
  ylab('Número de publicaciones') +
  theme_gg() +
  theme(legend.position = "none")
ggsave("figs/NumPubType.pdf", width = 5, height = 5, useDingbats=FALSE)

#Plot of # of type of publication (distinguishes thesis)
ggplot(d, aes(Type, fill = Subtype)) +
  geom_bar() +
  scale_fill_grey(name = "Sub-categoría") +
  xlab('Categoría de publicación') +
  ylab('Número de publicaciones') +
  theme_gg()
ggsave("figs/NumPubSubtype.pdf", width = 5, height = 5, useDingbats=FALSE)

#Plot of # of type of publication overtime
ggplot(d, aes(Year, fill = Type)) +
  geom_histogram(col="white")+
  xlab('Año de publicación') +
  ylab('Número de publicaciones') +
  scale_fill_grey(name = "Categoría") +
  theme_gg()
ggsave("figs/NumPubTime.pdf", width = 7, height = 5, useDingbats=FALSE)

#Plot of # of type of publication overtime (distinguishes thesis)
ggplot(d, aes(Year, fill = Subtype)) +
  geom_histogram(col="white")+
  xlab('Año de publicación') +
  ylab('Número de publicaciones') +
  scale_fill_grey(name = "Categoría") +
  theme_gg()
ggsave("figs/NumPubTimeSubtype.pdf", width = 7, height = 5, useDingbats=FALSE)

```










